version: '3.6'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: storehive_db # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - db-data:/var/lib/postgresql/data

  phppgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: adminpassword
      ports:
        - 8080:80

volumes:
  db-data: